"""Migração

Revision ID: f377140fea72
Revises: 
Create Date: 2024-11-29 09:17:22.224454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f377140fea72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('profissao', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vaga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('salario', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('id_candidato', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_candidato'], ['candidato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaga')
    op.drop_table('candidato')
    # ### end Alembic commands ###
